
import { Question, QuestionType } from './types';

const cleanUrl = (url: string | undefined): string | undefined => {
    if (!url) return undefined;
    return url.trim()
        .replace(/\s+/g, '') // Remove spaces
        .replace(/res\.ioe\.vnzedu/, 'res.ioe.vn/edu') // Fix domain typos
        .replace(/res\.ioe\.vii/, 'res.ioe.vn')
        .replace(/res\.ioe\.vm/, 'res.ioe.vn')
        .replace(/Audio\s*mp3/i, 'Audio.mp3') // Fix extension
        .replace(/ImageExam\s*(\d)/, 'ImageExam/$1') // Fix path separators
        .replace(/Olympic\s*ExamData/, 'OlympicExamData')
        .replace(/EOlympic\s*ExamData/, 'EOlympic/ExamData')
        .replace(/'/g, '') // Remove accidental quotes
        .replace(/Audio-mp3/i, 'Audio.mp3');
};

export const QUIZ_DATA: Question[] = [
    { id: 1, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Mary", "English songs.", "dance and", "sing", "likes to"], correctAnswer: "Mary likes to sing and dance English songs.", explanation: "Mary thích hát và nhảy các bài hát tiếng Anh." },
    { id: 2, type: QuestionType.FILL_IN_BLANK, questionText: "I _ _ Mai.", correctAnswer: "am", explanation: "I am Mai: Tôi là Mai." },
    { id: 3, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["name's", "My", "Elizabeth."], correctAnswer: "My name's Elizabeth.", explanation: "Tên tôi là Elizabeth." },
    { id: 4, type: QuestionType.MULTIPLE_CHOICE, questionText: "This is a ... desk.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206649526343286_566X320.jpg"), options: ["pink", "yellow", "blue", "green"], correctAnswer: "blue", explanation: "Nhìn tranh: Cái bàn màu xanh dương." },
    { id: 5, type: QuestionType.FILL_IN_BLANK, questionText: "Jimmy wants a hel_ _ _ for his birthday.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/11/30/636161049674300683_566X320.jpg"), correctAnswer: "met", explanation: "Helmet: Mũ bảo hiểm." },
    { id: 6, type: QuestionType.MULTIPLE_CHOICE, questionText: "A: Is that your classmate? - B: ...", options: ["Yes, he isn't.", "No, she isn’t.", "Yes, it is.", "No, I’m not."], correctAnswer: "Yes, it is.", explanation: "Câu hỏi với 'that' thường trả lời là 'Yes, it is' hoặc 'No, it isn't' trong ngữ cảnh xác định người/vật từ xa." },
    { id: 7, type: QuestionType.MULTIPLE_CHOICE, questionText: "... your name?", options: ["What", "What’s", "How’s", "Why’s"], correctAnswer: "What’s", explanation: "What's your name?" },
    { id: 8, type: QuestionType.MULTIPLE_CHOICE, questionText: "Nice to ... you!", options: ["meet", "go", "for", "come"], correctAnswer: "meet", explanation: "Nice to meet you." },
    { id: 9, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["after school.", "Peter", "and I", "don't", "play baseball"], correctAnswer: "Peter and I don't play baseball after school.", explanation: "Peter và tôi không chơi bóng chày sau giờ học." },
    { id: 10, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["new", "This is", "my", "school bag."], correctAnswer: "This is my new school bag.", explanation: "Đây là cặp sách mới của tôi." },
    { id: 11, type: QuestionType.MULTIPLE_CHOICE, questionText: "… many desks are there in your classroom?", options: ["How", "What", "Who", "Which"], correctAnswer: "How", explanation: "How many: Bao nhiêu." },
    { id: 12, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["What", "he", "doing?", "is"], correctAnswer: "What is he doing?", explanation: "Cậu ấy đang làm gì?" },
    { id: 13, type: QuestionType.MULTIPLE_CHOICE, questionText: "… many books are there on the bookshelf?", options: ["Who", "How", "Where", "What"], correctAnswer: "How", explanation: "How many: Bao nhiêu." },
    { id: 14, type: QuestionType.FILL_IN_BLANK, questionText: "That is Lan. _ _ _ is my friend.", correctAnswer: "She", explanation: "She is my friend." },
    { id: 15, type: QuestionType.FILL_IN_BLANK, questionText: "Where is Simon f_ _ m? – He’s from England.", correctAnswer: "ro", explanation: "From: Đến từ." },
    { id: 16, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["How", "spell", "do you", "his name?"], correctAnswer: "How do you spell his name?", explanation: "Bạn đánh vần tên cậu ấy như thế nào?" },
    { id: 17, type: QuestionType.FILL_IN_BLANK, questionText: "_ pen your book, please!", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/2-dt-52.jpg"), correctAnswer: "O", explanation: "Open: Mở." },
    { id: 18, type: QuestionType.FILL_IN_BLANK, questionText: "Hi, _ _ _ are you? – Fine, thanks.", correctAnswer: "how", explanation: "How are you?" },
    { id: 19, type: QuestionType.FILL_IN_BLANK, questionText: "Stand _ _ , please.", correctAnswer: "up", explanation: "Stand up: Đứng lên." },
    { id: 20, type: QuestionType.FILL_IN_BLANK, questionText: "Th_ t is my school. It’s very big.", correctAnswer: "a", explanation: "That: Kia là." },
    { id: 21, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["your", "room?", "it", "Is", "computer"], correctAnswer: "Is it your computer room?", explanation: "Đó có phải là phòng máy tính của bạn không?" },
    { id: 22, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the correct sentence.", options: ["I like play basketball.", "My brother is twelve year old.", "Tony plays football at break time.", "What are your name?"], correctAnswer: "Tony plays football at break time.", explanation: "Tony (ngôi thứ 3 số ít) + plays." },
    { id: 23, type: QuestionType.MULTIPLE_CHOICE, questionText: "What colour ... this?", options: ["it", "is", "that", "hi"], correctAnswer: "is", explanation: "What colour is this?" },
    { id: 24, type: QuestionType.FILL_IN_BLANK, questionText: "Let’s ma_ e a circle.", correctAnswer: "k", explanation: "Make a circle: Tạo thành vòng tròn." },
    { id: 25, type: QuestionType.FILL_IN_BLANK, questionText: "Is th_ _ _ any water in the fridge, mom?", correctAnswer: "ere", explanation: "Is there: Có không." },
    { id: 26, type: QuestionType.MULTIPLE_CHOICE, questionText: "Happy birthday, Alice. This doll is for ... .", options: ["I", "you", "he", "she"], correctAnswer: "you", explanation: "For you: Cho bạn." },
    { id: 27, type: QuestionType.FILL_IN_BLANK, questionText: "My friends are in the pla_ ground.", correctAnswer: "y", explanation: "Playground: Sân chơi." },
    { id: 28, type: QuestionType.FILL_IN_BLANK, questionText: "This _ _ a pen.", correctAnswer: "is", explanation: "This is." },
    { id: 29, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["is", "room?", "your", "What colour"], correctAnswer: "What colour is your room?", explanation: "Phòng của bạn màu gì?" },
    { id: 30, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["my", "not", "It", "is", "school bag."], correctAnswer: "It is not my school bag.", explanation: "Nó không phải cặp sách của tôi." },
    { id: 31, type: QuestionType.FILL_IN_BLANK, questionText: "Ma_ I go out, please?", correctAnswer: "y", explanation: "May I: Em có thể." },
    { id: 32, type: QuestionType.FILL_IN_BLANK, questionText: "Whe_ _ is your book? - It's on the shelf.", correctAnswer: "re", explanation: "Where: Ở đâu." },
    { id: 33, type: QuestionType.MULTIPLE_CHOICE, questionText: "What’s ... name?", options: ["you", "I", "his", "he"], correctAnswer: "his", explanation: "His name: Tên cậu ấy." },
    { id: 34, type: QuestionType.MULTIPLE_CHOICE, questionText: "D_SK", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/2-dt-56.jpg"), options: ["E", "A", "O", "U"], correctAnswer: "E", explanation: "DESK: Cái bàn." },
    { id: 35, type: QuestionType.MULTIPLE_CHOICE, questionText: "… is my father.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/11/30/636160979459463683_Audio.mp3"), options: ["This", "That", "It", "He"], correctAnswer: "He", explanation: "He is my father." },
    { id: 36, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["They", "in the", "classroom.", "aren't"], correctAnswer: "They aren't in the classroom.", explanation: "Họ không ở trong lớp học." },
    { id: 37, type: QuestionType.FILL_IN_BLANK, questionText: "Look _ _ the board.", correctAnswer: "at", explanation: "Look at: Nhìn vào." },
    { id: 38, type: QuestionType.FILL_IN_BLANK, questionText: "TABLE AND CHAI_", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/2-dt-29.jpg"), correctAnswer: "R", explanation: "CHAIR: Cái ghế." },
    { id: 39, type: QuestionType.MULTIPLE_CHOICE, questionText: "Listen ... the teacher.", options: ["to", "me", "you", "he"], correctAnswer: "to", explanation: "Listen to: Lắng nghe." },
    { id: 40, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the sentence that you hear:", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2019/11/29/637106243647920057_Audio.mp3"), options: ["I’m fine.", "I’m fine, thanks.", "Fine, thank you.", "I am fine, thank you."], correctAnswer: "I’m fine, thanks.", explanation: "Nghe audio." },
    { id: 41, type: QuestionType.FILL_IN_BLANK, questionText: "YE_ _ OW", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2019/11/29/637106207376666697_566X320.jpg"), correctAnswer: "LL", explanation: "YELLOW: Màu vàng." },
    { id: 42, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Take", "pens,", "out", "your", "Henry."], correctAnswer: "Take out your pens, Henry.", explanation: "Lấy bút ra nào Henry." },
    { id: 43, type: QuestionType.FILL_IN_BLANK, questionText: "My cla_ _ room is small.", correctAnswer: "ss", explanation: "Classroom: Lớp học." },
    { id: 44, type: QuestionType.FILL_IN_BLANK, questionText: "Good m_ rning, teacher!", correctAnswer: "o", explanation: "Morning: Buổi sáng." },
    { id: 45, type: QuestionType.FILL_IN_BLANK, questionText: "He's 8 years _ _ _ .", correctAnswer: "old", explanation: "Years old: Tuổi." },
    { id: 46, type: QuestionType.FILL_IN_BLANK, questionText: "RU_ BER", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/4-dt-31.jpg"), correctAnswer: "B", explanation: "RUBBER: Cục tẩy." },
    { id: 47, type: QuestionType.FILL_IN_BLANK, questionText: "Monkeys’ favourite fruits are ba_ _ nas.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/11/30/636161049301643698_566X320.jpg"), correctAnswer: "na", explanation: "Bananas: Quả chuối." },
    { id: 48, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["please.", "some", "me", "Give", "chalks,"], correctAnswer: "Give me some chalks, please.", explanation: "Làm ơn đưa tôi vài viên phấn." },
    { id: 49, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["erasers", "on", "How many", "are there", "the table?"], correctAnswer: "How many erasers are there on the table?", explanation: "Có bao nhiêu cục tẩy trên bàn?" },
    { id: 50, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["that", "Miss", "Is", "Lan?"], correctAnswer: "Is that Miss Lan?", explanation: "Đó có phải cô Lan không?" },
    { id: 51, type: QuestionType.FILL_IN_BLANK, questionText: "How _ _ _ _ crayons are there?", correctAnswer: "many", explanation: "How many: Bao nhiêu." },
    { id: 52, type: QuestionType.MULTIPLE_CHOICE, questionText: "He is ... farmer.", options: ["an", "a", "this", "am"], correctAnswer: "a", explanation: "A farmer: Một nông dân." },
    { id: 53, type: QuestionType.MULTIPLE_CHOICE, questionText: "Good ... , Jame. - Hi, Tom. How are you?", options: ["nice", "morning", "see", "my"], correctAnswer: "morning", explanation: "Good morning." },
    { id: 54, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Does", "volleyball", "or", "she like", "basketball?"], correctAnswer: "Does she like volleyball or basketball?", explanation: "Cô ấy thích bóng chuyền hay bóng rổ?" },
    { id: 55, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["large?", "school", "your", "Is"], correctAnswer: "Is your school large?", explanation: "Trường của bạn có rộng không?" },
    { id: 56, type: QuestionType.MULTIPLE_CHOICE, questionText: "My sister … books in the school library.", options: ["read", "reads", "to read", "reading"], correctAnswer: "reads", explanation: "My sister (số ít) + reads." },
    { id: 57, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["don't", "go to", "today.", "I", "school"], correctAnswer: "I don't go to school today.", explanation: "Hôm nay tôi không đi học." },
    { id: 58, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["his friends", "don’t like", "basketball.", "Peter", "and"], correctAnswer: "Peter and his friends don’t like basketball.", explanation: "Peter và bạn cậu ấy không thích bóng rổ." },
    { id: 59, type: QuestionType.FILL_IN_BLANK, questionText: "You are wel_ _ me.", correctAnswer: "co", explanation: "Welcome: Không có chi." },
    { id: 60, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["the", "at", "please!", "Look", "board,"], correctAnswer: "Look at the board, please!", explanation: "Hãy nhìn lên bảng." },
    { id: 61, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["He", "likes", "swimming."], correctAnswer: "He likes swimming.", explanation: "Cậu ấy thích bơi." },
    { id: 62, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["a", "That", "brown", "cat.", "is"], correctAnswer: "That is a brown cat.", explanation: "Đó là một con mèo màu nâu." },
    { id: 63, type: QuestionType.FILL_IN_BLANK, questionText: "LI_ _ _ _ _", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2019/11/29/637106247825727339_Audio.mp3"), correctAnswer: "STEN", explanation: "LISTEN: Nghe." },
    { id: 64, type: QuestionType.MULTIPLE_CHOICE, questionText: "Who’s that? - That’s ... .", options: ["my’s teacher", "me’s teacher", "my teacher", "me teacher"], correctAnswer: "my teacher", explanation: "My teacher: Giáo viên của tôi." },
    { id: 65, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Write", "the teacher", "says.", "what"], correctAnswer: "Write what the teacher says.", explanation: "Viết những gì giáo viên nói." },
    { id: 66, type: QuestionType.FILL_IN_BLANK, questionText: "Let’s mak_ a line.", correctAnswer: "e", explanation: "Make a line: Xếp hàng." },
    { id: 67, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["bag.", "is", "That", "school", "a green"], correctAnswer: "That is a green school bag.", explanation: "Kia là một cái cặp sách màu xanh lá." },
    { id: 68, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the correct order.", options: ["L, M, N, O, P, Q", "M, L, N, O, Q, P", "N, M, L, P, Q, O", "O, L, M, N, P, Q"], correctAnswer: "L, M, N, O, P, Q", explanation: "Thứ tự bảng chữ cái." },
    { id: 69, type: QuestionType.MULTIPLE_CHOICE, questionText: "He ... a newcomer.", options: ["are", "am", "is", "do"], correctAnswer: "is", explanation: "He is." },
    { id: 70, type: QuestionType.FILL_IN_BLANK, questionText: "What colour are the trousers? - They are _ _ _ _ .", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/11/30/636161050388519660_566X320.jpg"), correctAnswer: "blue", explanation: "Nhìn tranh: Màu xanh dương (blue)." },
    { id: 71, type: QuestionType.MULTIPLE_CHOICE, questionText: "Collins: Hello. My name is Collins. Barry: ... .", options: ["Nice to meet you", "Hi. See you later", "Goodbye", "Bye"], correctAnswer: "Nice to meet you", explanation: "Chào hỏi lịch sự." },
    { id: 72, type: QuestionType.FILL_IN_BLANK, questionText: "Unscramble this word: ’’OOBETKNO’’ -> ’’NOTEBO_ _ ’’.", correctAnswer: "OK", explanation: "NOTEBOOK: Quyển vở." },
    { id: 73, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["repeat", "me.", "after", "Please"], correctAnswer: "Please repeat after me.", explanation: "Hãy nhắc lại theo tôi." },
    { id: 74, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ _ , he is.", correctAnswer: "Yes", explanation: "Yes, he is." },
    { id: 75, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["go to", "This is", "school.", "we", "the way"], correctAnswer: "This is the way we go to school.", explanation: "Đây là cách chúng mình đi học." },
    { id: 76, type: QuestionType.FILL_IN_BLANK, questionText: "Put your books on the tabl_ .", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi%20Th%E1%BB%AD/Thi_trai_nghiem_2021/Lop3/images1/dt.jpg"), correctAnswer: "e", explanation: "Table: Bàn." },
    { id: 77, type: QuestionType.MULTIPLE_CHOICE, questionText: "Odd one out:", options: ["footballer", "singer", "teacher", "cooker"], correctAnswer: "cooker", explanation: "'Cooker' là nồi cơm điện/bếp nấu, các từ còn lại chỉ người." },
    { id: 78, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["is", "old.", "three", "years", "My brother"], correctAnswer: "My brother is three years old.", explanation: "Em trai tôi 3 tuổi." },
    { id: 79, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["your", "hands", "the table.", "Put", "on"], correctAnswer: "Put your hands on the table.", explanation: "Đặt tay lên bàn." },
    { id: 80, type: QuestionType.MULTIPLE_CHOICE, questionText: "What’s this? - ... .", options: ["That a picture", "These are pictures", "There are picture", "This is a picture"], correctAnswer: "This is a picture", explanation: "What's this -> This is..." },
    { id: 81, type: QuestionType.MULTIPLE_CHOICE, questionText: "I’d like some strawberries. – Here … are.", options: ["they", "them", "those", "these"], correctAnswer: "they", explanation: "Here they are." },
    { id: 82, type: QuestionType.MULTIPLE_CHOICE, questionText: "What is this? - ... .", options: ["It a apple", "Is a apple", "It’s a apple", "It’s an apple"], correctAnswer: "It’s an apple", explanation: "An apple (nguyên âm)." },
    { id: 83, type: QuestionType.MULTIPLE_CHOICE, questionText: "We play ... in the playground.", options: ["badminton", "football", "hide-and-seek", "baseball"], correctAnswer: "football", explanation: "Play football." },
    { id: 84, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["ruler?", "your", "Is", "it"], correctAnswer: "Is it your ruler?", explanation: "Nó có phải là thước kẻ của bạn không?" },
    { id: 85, type: QuestionType.MULTIPLE_CHOICE, questionText: "I have ... robot.", options: ["a", "an", "two", "and"], correctAnswer: "a", explanation: "A robot." },
    { id: 86, type: QuestionType.MULTIPLE_CHOICE, questionText: "Lucy and her ... draw picture in classroom.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206313103207623_Audio.mp3"), options: ["boys", "teachers", "friends", "girls"], correctAnswer: "friends", explanation: "Nghe audio: Friends." },
    { id: 87, type: QuestionType.FILL_IN_BLANK, questionText: "She is in _ _ _ music room.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206305315049944_Audio.mp3"), correctAnswer: "the", explanation: "In the music room." },
    { id: 88, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Be", "quiet,", "boys!"], correctAnswer: "Be quiet, boys!", explanation: "Trật tự nào các chàng trai." },
    { id: 89, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["in", "the sky.", "many", "There are", "clouds"], correctAnswer: "There are many clouds in the sky.", explanation: "Có nhiều mây trên bầu trời." },
    { id: 90, type: QuestionType.FILL_IN_BLANK, questionText: "Please dr_ _ a picture, children.", correctAnswer: "aw", explanation: "Draw: Vẽ." },
    { id: 91, type: QuestionType.FILL_IN_BLANK, questionText: "Can you he_ p me?", correctAnswer: "l", explanation: "Help: Giúp." },
    { id: 92, type: QuestionType.MULTIPLE_CHOICE, questionText: "Is ... a chair? - Yes, it is.", options: ["are", "it", "it’s", "his"], correctAnswer: "it", explanation: "Is it..." },
    { id: 93, type: QuestionType.MULTIPLE_CHOICE, questionText: "What colou... is this? – It’s pink.", options: ["t", "q", "r", "p"], correctAnswer: "r", explanation: "Colour." },
    { id: 94, type: QuestionType.MULTIPLE_CHOICE, questionText: "That’s Peter. ... is my friend.", options: ["I", "You", "She", "He"], correctAnswer: "He", explanation: "Peter -> He." },
    { id: 95, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["is", "friend.", "my", "Jenny"], correctAnswer: "Jenny is my friend.", explanation: "Jenny là bạn tôi." },
    { id: 96, type: QuestionType.MULTIPLE_CHOICE, questionText: "The elephant ... big and the mouse ... small.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/3-tn-63.jpg"), options: ["are - is", "are - are", "is - are", "is - is"], correctAnswer: "is - is", explanation: "Số ít -> is." },
    { id: 97, type: QuestionType.FILL_IN_BLANK, questionText: "Mary often gets up early so she _ _ never late for shool.", correctAnswer: "is", explanation: "She is." },
    { id: 98, type: QuestionType.FILL_IN_BLANK, questionText: "This _ _ my new school. I love my new school.", correctAnswer: "is", explanation: "This is." },
    { id: 99, type: QuestionType.MULTIPLE_CHOICE, questionText: "Is ... a flower? – Yes. That is a flower.", options: ["that’s", "that", "this", "this is"], correctAnswer: "that", explanation: "Is that..." },
    { id: 100, type: QuestionType.MULTIPLE_CHOICE, questionText: "My brother is ... years old.", options: ["two", "to", "too", "do"], correctAnswer: "two", explanation: "Two: Số 2." },
    { id: 101, type: QuestionType.MULTIPLE_CHOICE, questionText: "Simon can sing ... he cannot swim.", options: ["and", "end", "but", "or"], correctAnswer: "but", explanation: "But: Nhưng." },
    { id: 102, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["my", "book?", "I", "May", "close"], correctAnswer: "May I close my book?", explanation: "Em có thể gấp sách lại không?" },
    { id: 103, type: QuestionType.FILL_IN_BLANK, questionText: "Can you swim? - _ _ , I can’t.", correctAnswer: "No", explanation: "No, I can't." },
    { id: 104, type: QuestionType.MULTIPLE_CHOICE, questionText: "Hello, ... name is Scott.", options: ["he", "she", "it", "my"], correctAnswer: "my", explanation: "My name." },
    { id: 105, type: QuestionType.MULTIPLE_CHOICE, questionText: "Is this a book? – Yes, ... .", options: ["I am", "is it", "it is", "it isn’t"], correctAnswer: "it is", explanation: "Yes, it is." },
    { id: 106, type: QuestionType.FILL_IN_BLANK, questionText: "The teddy is betw_ _ _ the car and the robot.", correctAnswer: "een", explanation: "Between: Ở giữa." },
    { id: 107, type: QuestionType.FILL_IN_BLANK, questionText: "They _ _ _ my good friends.", correctAnswer: "are", explanation: "They are." },
    { id: 108, type: QuestionType.MULTIPLE_CHOICE, questionText: "That's my ... .", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Audio/2-tn-27.mp3"), options: ["schoolbag", "school gym", "school playground", "school"], correctAnswer: "schoolbag", explanation: "Nghe audio." },
    { id: 109, type: QuestionType.MULTIPLE_CHOICE, questionText: "Her old car is a ... Honda.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Audio/2-tn-61.mp3"), options: ["red", "black", "white", "pink"], correctAnswer: "red", explanation: "Nghe audio." },
    { id: 110, type: QuestionType.FILL_IN_BLANK, questionText: "Loo_ at the school.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Audio/1-dt-6.mp3"), correctAnswer: "k", explanation: "Look at." },
    { id: 111, type: QuestionType.MULTIPLE_CHOICE, questionText: "May I come ... ?", options: ["in", "at", "on", "to"], correctAnswer: "in", explanation: "Come in: Vào." },
    { id: 112, type: QuestionType.FILL_IN_BLANK, questionText: "W_ _ is she? – She is my new teacher.", correctAnswer: "ho", explanation: "Who: Ai." },
    { id: 113, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["teacher?", "Is", "your", "he"], correctAnswer: "Is he your teacher?", explanation: "Ông ấy có phải giáo viên của bạn không?" },
    { id: 114, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Here", "my", "is", "notebook."], correctAnswer: "Here is my notebook.", explanation: "Đây là vở của tôi." },
    { id: 115, type: QuestionType.FILL_IN_BLANK, questionText: "Lan’s school _ _ _ ground is large.", correctAnswer: "play", explanation: "Playground." },
    { id: 116, type: QuestionType.MULTIPLE_CHOICE, questionText: "Listen and choose the correct response", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2018/1/2/636504877346767030_Audio.mp3"), options: ["Yes, I am.", "This is my teddy.", "No, it isn’t.", "The teddy is Peter’s."], correctAnswer: "No, it isn’t.", explanation: "Is this your teddy? -> No, it isn't." },
    { id: 117, type: QuestionType.MULTIPLE_CHOICE, questionText: "Listen and tick:", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206377131960084_Audio.mp3"), options: ["My father is a teacher.", "My mother is a teacher", "My father is a doctor.", "My brother is a teacher."], correctAnswer: "My father is a teacher.", explanation: "Nghe audio." },
    { id: 118, type: QuestionType.FILL_IN_BLANK, questionText: "I like to s_ ng.", correctAnswer: "i", explanation: "Sing: Hát." },
    { id: 119, type: QuestionType.FILL_IN_BLANK, questionText: "Sit d_ _ _ , Tommy.", correctAnswer: "own", explanation: "Down." },
    { id: 120, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["from", "My new", "is", "friend", "France."], correctAnswer: "My new friend is from France.", explanation: "Bạn mới của tôi đến từ Pháp." },
    { id: 121, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Let's", "play.", "outside", "go", "and"], correctAnswer: "Let's go outside and play.", explanation: "Hãy ra ngoài chơi nào." },
    { id: 122, type: QuestionType.FILL_IN_BLANK, questionText: "That is a blue s_ _ _ .", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/23/635208321994581633_566X320.jpg"), correctAnswer: "ock", explanation: "Sock: Chiếc tất." },
    { id: 123, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ _ _ are my crayons.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2018/1/2/636504891760936521_Audio.mp3"), correctAnswer: "They", explanation: "They are my crayons." },
    { id: 124, type: QuestionType.MULTIPLE_CHOICE, questionText: "That is my school gym. ... new.", options: ["Its", "It's is", "It's", "Its's"], correctAnswer: "It's", explanation: "It is." },
    { id: 125, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["My friends", "in", "the playground.", "are"], correctAnswer: "My friends are in the playground.", explanation: "Bạn tôi đang ở sân chơi." },
    { id: 126, type: QuestionType.FILL_IN_BLANK, questionText: "It's the _ rt room.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/4-dt-11.jpg"), correctAnswer: "A", explanation: "Art room: Phòng mỹ thuật." },
    { id: 127, type: QuestionType.MULTIPLE_CHOICE, questionText: "These are your new … and ….", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2018/1/2/636504878931926679_Audio.mp3"), options: ["bookcases – boards", "tables – computers", "beds – chairs", "tables – chairs"], correctAnswer: "tables – chairs", explanation: "Nghe audio." },
    { id: 128, type: QuestionType.MULTIPLE_CHOICE, questionText: "Hello my fr...end.", options: ["u", "i", "w", "o"], correctAnswer: "i", explanation: "Friend." },
    { id: 129, type: QuestionType.FILL_IN_BLANK, questionText: "May I co_ _ in?", correctAnswer: "me", explanation: "Come in." },
    { id: 130, type: QuestionType.MULTIPLE_CHOICE, questionText: "... colour is your bag?", options: ["What", "Where", "When", "How"], correctAnswer: "What", explanation: "What colour." },
    { id: 131, type: QuestionType.FILL_IN_BLANK, questionText: "Gi_ e me the book, please.", correctAnswer: "v", explanation: "Give: Đưa." },
    { id: 132, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["down.", "your pencil", "Put"], correctAnswer: "Put your pencil down.", explanation: "Đặt bút xuống." },
    { id: 133, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["my pencils.", "those are", "her crayons", "These are", "and"], correctAnswer: "These are her crayons and those are my pencils.", explanation: "Đây là bút màu của cô ấy và kia là bút chì của tôi." },
    { id: 134, type: QuestionType.FILL_IN_BLANK, questionText: "What’s your nam_ ? - My name is Alan.", correctAnswer: "e", explanation: "Name." },
    { id: 135, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["cats", "many", "How", "there?", "are"], correctAnswer: "How many cats are there?", explanation: "Có bao nhiêu con mèo?" },
    { id: 136, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["learn", "the gym.", "in", "PE lessons", "We"], correctAnswer: "We learn PE lessons in the gym.", explanation: "Chúng tôi học Thể dục ở phòng tập." },
    { id: 137, type: QuestionType.MULTIPLE_CHOICE, questionText: "The ... is short.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206358438759251_Audio.mp3"), options: ["ruler", "pencil", "pen", "rubber"], correctAnswer: "pencil", explanation: "Nghe audio." },
    { id: 138, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ at is my ruler.", correctAnswer: "Th", explanation: "That." },
    { id: 139, type: QuestionType.FILL_IN_BLANK, questionText: "I’m fine, thanks. How a_ _ _ t you?", correctAnswer: "bou", explanation: "About." },
    { id: 140, type: QuestionType.MULTIPLE_CHOICE, questionText: "Listen and tick:", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206368383620718_Audio.mp3"), options: ["Is that girl Mary? - Yes, she is.", "Is that boy Mary? - Yes, he is.", "Is that pen Mary? - Yes, it is.", "Is that room Mary? - Yes, it is."], correctAnswer: "Is that girl Mary? - Yes, she is.", explanation: "Nghe audio." },
    { id: 141, type: QuestionType.FILL_IN_BLANK, questionText: "_ ite", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi%20Th%E1%BB%AD/Thi_trai_nghiem_2021/Lop3/dt-36.mp3"), correctAnswer: "K", explanation: "Kite: Cái diều." },
    { id: 142, type: QuestionType.FILL_IN_BLANK, questionText: "b_ g", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/11/30/636161052058989367_Audio.mp3"), correctAnswer: "a", explanation: "Bag: Cái cặp." },
    { id: 143, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["bag", "My", "small.", "is", "school"], correctAnswer: "My school bag is small.", explanation: "Cặp sách của tôi nhỏ." },
    { id: 144, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["three crayons", "are", "There", "the table.", "on"], correctAnswer: "There are three crayons on the table.", explanation: "Có 3 bút màu trên bàn." },
    { id: 145, type: QuestionType.MULTIPLE_CHOICE, questionText: "… do you like? – I like riding a horse.", options: ["When", "How", "What", "Who"], correctAnswer: "What", explanation: "What do you like." },
    { id: 146, type: QuestionType.MULTIPLE_CHOICE, questionText: "What is her favorite colour?", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Audio/3-tn-68.mp3"), options: ["red", "orange", "yellow", "green"], correctAnswer: "red", explanation: "Nghe audio." },
    { id: 147, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ _ CATS", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2019/11/29/637106207179634996_566X320.jpg"), correctAnswer: "TWO", explanation: "TWO CATS: 2 con mèo." },
    { id: 148, type: QuestionType.FILL_IN_BLANK, questionText: "sch_ _ l", correctAnswer: "oo", explanation: "School." },
    { id: 149, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["play", "together.", "Let’s", "chess"], correctAnswer: "Let’s play chess together.", explanation: "Cùng chơi cờ nào." },
    { id: 150, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ that your new friend? - No, he isn’t.", correctAnswer: "Is", explanation: "Is that." },
    { id: 151, type: QuestionType.MULTIPLE_CHOICE, questionText: "Do you like goldfish?", options: ["Yes, I am.", "Yes, I can.", "Yes, it is.", "Yes, I do."], correctAnswer: "Yes, I do.", explanation: "Yes, I do." },
    { id: 152, type: QuestionType.MULTIPLE_CHOICE, questionText: "Good mo...ning, Peter.", options: ["w", "t", "r", "q"], correctAnswer: "r", explanation: "Morning." },
    { id: 153, type: QuestionType.FILL_IN_BLANK, questionText: "We are on the _ _ _ _ _ because it’s very hot today.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/11/30/636161048841330105_566X320.jpg"), correctAnswer: "beach", explanation: "Beach: Bãi biển." },
    { id: 154, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["clap your hands.", "and", "Sing"], correctAnswer: "Sing and clap your hands.", explanation: "Hát và vỗ tay." },
    { id: 155, type: QuestionType.FILL_IN_BLANK, questionText: "Gi_ e me the book, please.", correctAnswer: "v", explanation: "Give." },
    { id: 156, type: QuestionType.FILL_IN_BLANK, questionText: "Circle the ans_ er.", correctAnswer: "w", explanation: "Answer: Câu trả lời." },
    { id: 157, type: QuestionType.MULTIPLE_CHOICE, questionText: "That pen is ... .", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206658068133248_566X320.jpg"), options: ["yellow", "pink", "black", "brown"], correctAnswer: "brown", explanation: "Màu nâu." },
    { id: 158, type: QuestionType.MULTIPLE_CHOICE, questionText: "... are my shoes.", options: ["This", "That", "It", "These"], correctAnswer: "These", explanation: "These are." },
    { id: 159, type: QuestionType.MULTIPLE_CHOICE, questionText: "This gift is ... you.", options: ["on", "in", "for", "at"], correctAnswer: "for", explanation: "For you." },
    { id: 160, type: QuestionType.MULTIPLE_CHOICE, questionText: "Goodbye! - Bye, see you ... .", options: ["hi", "later", "hello", "good"], correctAnswer: "later", explanation: "See you later." },
    { id: 161, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["I", "play chess", "in the classroom."], correctAnswer: "I play chess in the classroom.", explanation: "Tôi chơi cờ trong lớp." },
    { id: 162, type: QuestionType.FILL_IN_BLANK, questionText: "Cl_ _ n your teeth, please.", correctAnswer: "ea", explanation: "Clean: Làm sạch (đánh răng)." },
    { id: 163, type: QuestionType.MULTIPLE_CHOICE, questionText: "That is a small ... .", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206362622842600_Audio.mp3"), options: ["board", "bus", "box", "boat"], correctAnswer: "box", explanation: "Nghe audio." },
    { id: 164, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Sit", ", please.", "down"], correctAnswer: "Sit down, please.", explanation: "Mời ngồi." },
    { id: 165, type: QuestionType.FILL_IN_BLANK, questionText: "It's a pink ha_ .", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/4-dt-8.jpg"), correctAnswer: "t", explanation: "Hat: Cái mũ." },
    { id: 166, type: QuestionType.MULTIPLE_CHOICE, questionText: "… is she? – She is my sister.", options: ["What", "When", "Who", "How"], correctAnswer: "Who", explanation: "Who is she?" },
    { id: 167, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["my", "classroom.", "is", "This"], correctAnswer: "This is my classroom.", explanation: "Đây là lớp của tôi." },
    { id: 168, type: QuestionType.MULTIPLE_CHOICE, questionText: "Hello, how a..e you?", options: ["u", "r", "e", "i"], correctAnswer: "r", explanation: "Are." },
    { id: 169, type: QuestionType.MULTIPLE_CHOICE, questionText: "What is your name? - ... .", options: ["Her name is Mary.", "His name is Alan.", "My name is Lan.", "Your name is Peter."], correctAnswer: "My name is Lan.", explanation: "My name is..." },
    { id: 170, type: QuestionType.MULTIPLE_CHOICE, questionText: "This ... my school.", options: ["are", "is", "you", "bye"], correctAnswer: "is", explanation: "This is." },
    { id: 171, type: QuestionType.MULTIPLE_CHOICE, questionText: "H...llo, how are you?", options: ["u", "e", "i", "a"], correctAnswer: "e", explanation: "Hello." },
    { id: 172, type: QuestionType.FILL_IN_BLANK, questionText: "It is _ _ ice-cream.", correctAnswer: "an", explanation: "An ice-cream." },
    { id: 173, type: QuestionType.MULTIPLE_CHOICE, questionText: "What ... is this? – It’s blue.", options: ["colour", "colours", "colour’s", "coulor"], correctAnswer: "colour", explanation: "Colour." },
    { id: 174, type: QuestionType.FILL_IN_BLANK, questionText: "These are t_ o cats.", correctAnswer: "w", explanation: "Two: Hai." },
    { id: 175, type: QuestionType.FILL_IN_BLANK, questionText: "Nice to m_ _ t you!", correctAnswer: "ee", explanation: "Meet." },
    { id: 176, type: QuestionType.MULTIPLE_CHOICE, questionText: "This is Tom and that … Mary.", options: ["am", "is", "are", "have"], correctAnswer: "is", explanation: "That is." },
    { id: 177, type: QuestionType.MULTIPLE_CHOICE, questionText: "She ... my friend.", options: ["are", "is", "me", "I"], correctAnswer: "is", explanation: "She is." },
    { id: 178, type: QuestionType.FILL_IN_BLANK, questionText: "I draw a pictu_ _ in the room.", correctAnswer: "re", explanation: "Picture: Bức tranh." },
    { id: 179, type: QuestionType.MULTIPLE_CHOICE, questionText: "Nice ... meet you, too.", options: ["for", "to", "from", "me"], correctAnswer: "to", explanation: "Nice to meet you." },
    { id: 180, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Look", "at", "picture.", "that", "blue"], correctAnswer: "Look at that blue picture.", explanation: "Nhìn vào bức tranh màu xanh kia." },
    { id: 181, type: QuestionType.MULTIPLE_CHOICE, questionText: "Bob: What is this? - Peter: ...", options: ["His name is Hien.", "It is a ruler.", "It’s an ruler.", "It is my friend."], correctAnswer: "It is a ruler.", explanation: "Trả lời cho 'What is this'." },
    { id: 182, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Does", "have", "hair?", "she", "long"], correctAnswer: "Does she have long hair?", explanation: "Cô ấy có tóc dài không?" },
    { id: 183, type: QuestionType.FILL_IN_BLANK, questionText: "Those are f_ ve boxes.", correctAnswer: "i", explanation: "Five." },
    { id: 184, type: QuestionType.FILL_IN_BLANK, questionText: "Is t_ is your eraser?", correctAnswer: "h", explanation: "This." },
    { id: 185, type: QuestionType.MULTIPLE_CHOICE, questionText: "What is this? – It is ... ice cream.", options: ["a", "an", "these", "that"], correctAnswer: "an", explanation: "An ice cream." },
    { id: 186, type: QuestionType.MULTIPLE_CHOICE, questionText: "Listen and tick:", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206369453938598_Audio.mp3"), options: ["I’ve got two rulers.", "I’ve got two erasers.", "I’ve got two scissors.", "I’ve got two eggs."], correctAnswer: "I’ve got two erasers.", explanation: "Nghe audio." },
    { id: 187, type: QuestionType.MULTIPLE_CHOICE, questionText: "Look! That is a ... kite!", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/23/635208267529931187_566X320.jpg"), options: ["green", "red", "blue", "brown"], correctAnswer: "blue", explanation: "Nhìn tranh: Màu xanh dương." },
    { id: 188, type: QuestionType.FILL_IN_BLANK, questionText: "Nice to meet you, t_ _ .", correctAnswer: "oo", explanation: "Too." },
    { id: 189, type: QuestionType.MULTIPLE_CHOICE, questionText: "Be … Don’t make noise.", options: ["lazy", "quiet", "funny", "angry"], correctAnswer: "quiet", explanation: "Be quiet: Trật tự." },
    { id: 190, type: QuestionType.FILL_IN_BLANK, questionText: "Listen _ _ the teacher carefully.", correctAnswer: "to", explanation: "Listen to." },
    { id: 191, type: QuestionType.FILL_IN_BLANK, questionText: "Giv_ me the crayon, please.", correctAnswer: "e", explanation: "Give." },
    { id: 192, type: QuestionType.MULTIPLE_CHOICE, questionText: "... do you like? – I like milk.", options: ["How", "What", "When", "Who"], correctAnswer: "What", explanation: "What do you like?" },
    { id: 193, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ ain", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi%20Th%E1%BB%AD/Thi_trai_nghiem_2021/Lop3/dt-37.mp3"), correctAnswer: "Tr", explanation: "Train: Tàu hỏa." },
    { id: 194, type: QuestionType.FILL_IN_BLANK, questionText: "H_ _ many students in your class?", correctAnswer: "ow", explanation: "How many." },
    { id: 195, type: QuestionType.FILL_IN_BLANK, questionText: "I'm five years _ ld.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/2-dt-32.jpg"), correctAnswer: "o", explanation: "Old." },
    { id: 196, type: QuestionType.FILL_IN_BLANK, questionText: "I have _ _ apple.", correctAnswer: "an", explanation: "An apple." },
    { id: 197, type: QuestionType.FILL_IN_BLANK, questionText: "What do you do at b_ _ _ k time?", correctAnswer: "rea", explanation: "Break time: Giờ ra chơi." },
    { id: 198, type: QuestionType.MULTIPLE_CHOICE, questionText: "Is your school new? - Yes, ... .", options: ["is it", "its is", "it is", "is its"], correctAnswer: "it is", explanation: "Yes, it is." },
    { id: 199, type: QuestionType.FILL_IN_BLANK, questionText: "SCHOOL-B_ G", correctAnswer: "A", explanation: "SCHOOL-BAG: Cặp sách." },
    { id: 200, type: QuestionType.FILL_IN_BLANK, questionText: "Point to your frie_ _ , please.", correctAnswer: "nd", explanation: "Friend." }
];
